---

contentqa:
  api_key: aa22c5ec71f95032dbcba4afc2041deb
  repository:
    username: changeme
    password: changeme
    host: 192.168.50.2
    port: 5984
    endpoints:
      dpla: dpla
      dashboard: dashboard